# Problem Set 1, due March 1 by midnight

The goal of this problem set is to replicate and extend the results of  Jean et al.'s 2016 paper, "Combining satellite imagery and machine learning to predict poverty." This problem set will be challenging and time-consuming, so I suggest you start immediately. Your first step should be to carefully read <a href="https://pdfs.semanticscholar.org/1b3a/c4b4187a3dbc9373869e7774b1dc63f748d2.pdf">the original paper</a>  as well as the <a href="http://science.sciencemag.org/content/sci/suppl/2016/08/19/353.6301.790.DC1/Jean.SM.pdf">supplementary materials</a>.

For this assignment, we will focus on the country of Rwanda. You will need to download three distinct datasets, including DHS data, satellite data from the Google Maps API, as well as nighttime luminosity data. The DHS data requires registration (which can take several days to be approved), and the Google Maps API is rate-limited, so it will necessarily take you several days to download the requisite data, so make sure to **get started on those steps asap**. The deep learning section may also take several hours to compute (or days, if you have a slow computer), so don't save it until the last minute.

## Overview of the problem set

These are the key steps in the problem set:

1. Download satellite night lights images from NOAA
2. Download DHS data for Rwanda
3. Test whether night lights data can predict wealth, as observed in DHS
4. Download daytime satellite imagery from Google Maps
5. Test whether basic features of daytime imagery can predict wealth
6. Extract features from daytime imagery using deep learning libraries
7. Replicate final model and results of Jean et al (2016)
8. Construct maps showing the predicted distribution of wealth in Rwanda


# 1. Download nightlights for Rwanda

- **INPUT**:
 - None
- **OUTPUT**: 
 - `F182010.v4d_web.stable_lights.avg_vis.tif`: Single image file giving nightlights intensity around the world

Go to the [DMSP-OLS website](https://ngdc.noaa.gov/eog/dmsp/downloadV4composites.html) and download the satellite nighttime luminosity data (roughly 400MB). We will use the one from 2010. The archive they provide constains several files. Feel free to explore these files. We will only be using the file F182010.v4d_web.stable_lights.avg_vis.tif.

A code snippet to get you started is below.

In [3]:
import wget

night_image_url = 'https://ngdc.noaa.gov/eog/data/web_data/v4composites/F182010.v4.tar'
tar = wget.download(night_image_url)

In [20]:
%%sh
mkdir nightlights
tar -zxvf F182010.v4.tar -C nightlights/
gzip -d nightlights/F182010.v4d_web.stable_lights.avg_vis.tif.gz
rm nightlights/*.gz
mv F182010.v4.tar nightlights/

F182010.v4d_web.avg_vis.tif.gz
F182010.v4d_web.cf_cvg.tif.gz
F182010.v4d_web.stable_lights.avg_vis.tif.gz
README_V4.txt
mkdir: cannot create directory ‘nightlights’: File exists
gzip: nightlights/F182010.v4d_web.stable_lights.avg_vis.tif already exists;	not overwritten


# 2. Download Rwandan DHS and construct cluster-level aggregates

- **INPUT**: 
  - `rwanda_clusters_location.csv`: Coordinates of the centroid of each cluster
- **OUTPUT**: 
  - `rwanda_cluster_avg_asset_2010.csv`: Comma-delimited file indicated average wealth of each cluster 

[Demographic and Health Surveys (DHS)](http://dhsprogram.com/What-We-Do/Survey-Types/DHS.cfm) are nationally-representative household surveys that provide data for a wide range of monitoring and impact evaluation indicators in the areas of population, health, and nutrition. For this assignment, you will need to download the [2010 Rwandan DHS data](http://dhsprogram.com/what-we-do/survey/survey-display-364.cfm). **This requires registration, so start early!** Do not forget to request for the GPS dataset. Make sure you understand the structure of the data before starting.

Your immediate goal is to take the raw survey data, covering 12,540 households, and compute the average household wealth for each survey cluster (think of a cluster as a village). Refer to the file `Recode6_DHS_22March2013_DHSG4.pdf` for information on these data.

Save your output as `rwanda_cluster_avg_asset_2010.csv` and check that it matches the file that we have provided. You will use this file as input to the next step in the assignment.

Hints:
- `Household Recode` contains all the attributes of each household. It provides datasets with different formats. Feel free to explore the data. You can use `RWHR61FL.DAT` file in Flat ASCII data (.dat) format.
- `RWHR61FL.DCF` describes the attributes and the location of each attribute.
- Geographic Datasets: `rwge61fl.zip` contains the location of each cluster in Rwanda. It is in the format of shapefile, which needs QGIS or other GIS softwares to open. For those who are not familiar with GIS tools or who want a shortcut, you can also sue the file `rwanda_clusters_location.csv` provided with the problem set.

For reference, the cluster locations, overlaid on the nightlights data, are shown in the figure below.
<img src="figure/map1.png" alt="Map" style="width: 600px;"/>

In [447]:
import pandas as pd

clusters_loc = pd.read_csv('provided/rwanda_clusters_location.csv', dtype={'DHSCLUST':int})
clusters_loc = clusters_loc[['DHSCLUST', 'LATNUM', 'LONGNUM']]
clusters_loc.columns = ['cluster', 'latitude', 'longitude']

clusters_loc.head()


cluster  latitude  longitude
0        1 -2.532818  29.684726
1        2 -1.833858  30.310689
2        3 -1.888155  29.478298
3        4 -2.366763  30.521692
4        5 -2.171266  30.018541

In [448]:
# for these indices, refer to 
# diid17/rwandan-dhs/RWHR61FL.DCF
def value (line, start, length):
    return line[start:start+length]

def cluster_num (line):
    return int(value(line, 16, 8))

def wealth_index (line):
    w = value(line, 231, 8)
    return int(w)/100000

dataset =  {
    'cluster': cluster_num,
    'wlthindf': wealth_index
}

with open('rwandan-dhs/RWHR61FL.DAT','r') as f:
    process = lambda line: [fn(line) for fn in dataset.values()]
    rows = [process(l) for l in f]
    dhs = pd.DataFrame(rows, columns=dataset.keys())
    
dhs.head()

wlthindf  cluster
0   3.07037      121
1   1.48863      121
2   1.93735      121
3   0.14170      121
4  -0.07971      121

In [449]:
#      find the mean househould income of all homes in that cluster
mean_wealth = dhs.groupby('cluster').median()
cluster_avg_asset = pd.merge(clusters_loc,
                      mean_wealth,
                      left_on='cluster',
                      right_index=True)

cluster_avg_asset.head()

cluster  latitude  longitude  wlthindf
0        1 -2.532818  29.684726 -0.531405
1        2 -1.833858  30.310689 -0.409830
2        3 -1.888155  29.478298 -0.478115
3        4 -2.366763  30.521692 -0.435960
4        5 -2.171266  30.018541 -0.449480

In [466]:
import numpy as np

# Now we will check that it matches the file that we have provided.
correct = pd.read_csv('intermediate_files/rwanda_cluster_avg_asset_2010.csv')

# Some arithmetic issues are causing slight (~10^-7) differences in median calculations
# compared to the cannonical CSV:
#
#    (merged['wlthindf'].values[2], correct['wlthindf'].values[2])
#
# So, I use numpy.allclose() on this column to check for equality.
# Also, this method doesn't care about column ordering!
#
def fuzzy_compare (df1, df2):
    fuzzy_col_compares = [np.allclose(df1[col], df2[col]) for col in df1.columns]
    return np.all(fuzzy_col_compares)

fuzzy_compare(merged, correct)

True

In [451]:
# Write my results to CSV
cluster_avg_asset.to_csv('rwanda_cluster_avg_asset_2010.csv')

# 3. Test whether night lights data can predict wealth, as observed in DHS

Now that you have "ground truth" measures of average cluster wealth, your goal is to understand whether the nightlights data can be used to predict wealth. First, merge the DHS and nightlights data, and then fit a model of wealth on nightlights.

## 3.1 Merge nightlights and DHS data at cluster level
- **INPUT**: 
 - `F182010.v4d_web.stable_lights.avg_vis.tif`: Nightlights data, from Step 1
 - `rwanda_cluster_avg_asset_2010.csv`: DHS cluster averages, from Step 2
- **OUTPUT**: Merged datasets
 - `DHS_nightlights.csv`: Merged dataset with 492 rows, and 6 columns (one indicates average cluster wealth, 5 nightlights features)
 - Scatterplot of nightlights vs. DHS wealth

Perform a "spatial join" to compute the average nighttime luminosity for each of the DHS clusters. To do this, you should take the average of the luminosity values for the nightlights locations surrounding the cluster centroid.

Save your output as `DHS_nightlights.csv` and check that it is the same as the file we have provided.

Create a scatterplot showing the relationship between average cluster wealth (y-axis) and average nighttime luminosity (x-axis). Your scatterplot should have one dot for each of the 492 DHS clusters. Report the R^2 of the regression line.

Hints:
 - The resolution of each pixel in the nightlight image is about 1km. Use 10 pixels X 10 pixels to average the luminosity of each cluster.
 - Start by just taking the **Mean** of the luminosity in the 100 pixels and comparing this to cluster average wealth. If you like, you could also compute other luminosity characteristics of each cluster, such as the **Max**, **Min**, **Standard Deviation** of the 100 pixel values, but this step is not required. Note that the file we provide (`DHS_nightlights.csv`) has these added features.
 - To read the raw raster (nightlights) files, we recommend using the GDAL library. Use `conda install gdal` to install the GDAL library. We have provided some helper code for this below.

In [276]:
%%sh

# Here are my setup steps on ubuntu yakkety (no anaconda)

sudo apt-get install libgdal-dev
sudo apt-get build-dep gdal
export CPLUS_INCLUDE_PATH=/usr/include/gdal
export C_INCLUDE_PATH=/usr/include/gdal
sudo pip3 install GDAL==1.10.0 

In [487]:
import time
import os
import os.path
from osgeo import gdal, ogr, osr
from scipy import ndimage
from scipy import misc
# python3
from io import BytesIO
gdal.UseExceptions()
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import gridspec
%matplotlib inline
import urllib

# Helper function to read a raster file
def read_raster(raster_file):
    """
    Function
    --------
    read_raster

    Given a raster file, get the pixel size, pixel location, and pixel value

    Parameters
    ----------
    raster_file : string
        Path to the raster file

    Returns
    -------
    x_size : float
        Pixel size
    top_left_x_coords : numpy.ndarray  shape: (number of columns,)
        Longitude of the top-left point in each pixel
    top_left_y_coords : numpy.ndarray  shape: (number of rows,)
        Latitude of the top-left point in each pixel
    centroid_x_coords : numpy.ndarray  shape: (number of columns,)
        Longitude of the centroid in each pixel
    centroid_y_coords : numpy.ndarray  shape: (number of rows,)
        Latitude of the centroid in each pixel
    bands_data : numpy.ndarray  shape: (number of rows, number of columns, 1)
        Pixel value
    """
    raster_dataset = gdal.Open(raster_file, gdal.GA_ReadOnly)
    # get project coordination
    proj = raster_dataset.GetProjectionRef()
    bands_data = []
    # Loop through all raster bands
    for b in range(1, raster_dataset.RasterCount + 1):
        band = raster_dataset.GetRasterBand(b)
        bands_data.append(band.ReadAsArray())
        no_data_value = band.GetNoDataValue()
    bands_data = np.dstack(bands_data)
    rows, cols, n_bands = bands_data.shape

    # Get the metadata of the raster
    geo_transform = raster_dataset.GetGeoTransform()
    (upper_left_x, x_size, x_rotation, upper_left_y, y_rotation, y_size) = geo_transform
    
    # Get location of each pixel
    x_size = 1.0 / int(round(1 / float(x_size)))
    y_size = - x_size
    y_index = np.arange(bands_data.shape[0])
    x_index = np.arange(bands_data.shape[1])
    top_left_x_coords = upper_left_x + x_index * x_size
    top_left_y_coords = upper_left_y + y_index * y_size
    # Add half of the cell size to get the centroid of the cell
    centroid_x_coords = top_left_x_coords + (x_size / 2)
    centroid_y_coords = top_left_y_coords + (y_size / 2)

    return (x_size, top_left_x_coords, top_left_y_coords, centroid_x_coords, centroid_y_coords, bands_data)


# Helper function to get the pixel index of the point
def get_cell_idx(lon, lat, top_left_x_coords, top_left_y_coords):
    """
    Function
    --------
    get_cell_idx

    Given a point location and all the pixel locations of the raster file,
    get the column and row index of the point in the raster

    Parameters
    ----------
    lon : float
        Longitude of the point
    lat : float
        Latitude of the point
    top_left_x_coords : numpy.ndarray  shape: (number of columns,)
        Longitude of the top-left point in each pixel
    top_left_y_coords : numpy.ndarray  shape: (number of rows,)
        Latitude of the top-left point in each pixel
    
    Returns
    -------
    lon_idx : int
        Column index
    lat_idx : int
        Row index
    """
    lon_idx = np.where(top_left_x_coords < lon)[0][-1]
    lat_idx = np.where(top_left_y_coords > lat)[0][-1]
    return lon_idx, lat_idx

In [453]:
# this illustrates how you can read the nightlight image
raster_file = 'nightlights/F182010.v4d_web.stable_lights.avg_vis.tif'
x_size, top_left_x_coords, top_left_y_coords, centroid_x_coords, centroid_y_coords, bands_data = read_raster(raster_file)

# save the result in compressed format - see https://docs.scipy.org/doc/numpy/reference/generated/numpy.savez.html
np.savez('nightlight.npz', top_left_x_coords=top_left_x_coords, top_left_y_coords=top_left_y_coords, bands_data=bands_data)

In [462]:
# find the idx in array of the one value closest to `value`
def find_idx_of_nearest (array, value): return (np.abs(array-value)).argmin()
# Returns x index of the pixel at longitude `long`.
def x_index (longt): return find_idx_of_nearest(centroid_x_coords, longt)
# Returns y index of the pixel at latitude `lat`.
def y_index (lat):  return find_idx_of_nearest(centroid_y_coords, lat)
    
ex_longt = cluster_avg_asset.iloc[0]['longitude']
ex_lat = cluster_avg_asset.iloc[0]['latitude']
x_index(ex_long), y_index(ex_lat)

def surrounding_ten_pixels (lat, longt):
    '''
    Returns 10x10x1 array of lumosity values
    surroundoing lat, long
    from the band data.
    '''
    x_i,y_i = x_index(longt), y_index(lat)
    return bands_data[y_i-5:y_i+5, x_i-5:x_i+5]

surrounding_ten_pixels(ex_lat, ex_longt).shape == (10, 10, 1)

True

In [463]:
from functools import partial

# for each cluster,
def lumosity (fn, cluster):
    longt = cluster['longitude']
    lat = cluster['latitude']
    # find 10x10 pixel value array around this coordinate
    pixels = surrounding_ten_pixels(lat, longt)
    # reduce fn (e.g. np.mean) over that array
    reduced = fn(pixels)
    # return the reduced value
    return reduced

def lumosity_series (fn, name):
    s = cluster_avg_asset.apply(
        partial(lumosity, fn), 
        axis=1)
    s.name = name
    return s

def lumosity_df (columns):
    series = [lumosity_series(method, name) for name, method in columns.items()]
    return pd.concat(
        [cluster_avg_asset] + series,
        axis=1)

columns = {
  'max_': np.max,
  'mean_': np.mean,
  'median_': np.median,
  'min_': np.min,
  'std_': np.std,
}

wealth_nightlights = lumosity_df(columns)
wealth_nightlights = wealth_nightlights.rename(columns = {
    'wlthindf': 'wealth',
    'cluster': 'id'
}).drop(['latitude', 'longitude'], axis=1)

wealth_nightlights.head()



id    wealth  median_  min_  max_  mean_      std_
0   1 -0.531405      0.0     0     6   0.06  0.596992
1   2 -0.409830      0.0     0     0   0.00  0.000000
2   3 -0.478115      0.0     0     0   0.00  0.000000
3   4 -0.435960      0.0     0     0   0.00  0.000000
4   5 -0.449480      0.0     0     0   0.00  0.000000

In [464]:
# Now check to make sure our data is fuzzily correct to the provided nightlights data
correct = pd.read_csv('intermediate_files/DHS_nightlights.csv')
fuzzy_compare(correct, wealth_nightlights)


True

In [465]:
# Now save our output data
df.to_csv('DHS_nightlights.csv')

## 3.2. Fit a model of wealth as a function of nightlights
- **INPUT**: 
 - `DHS_nightlights.csv`, from Step 3.1
- **OUTPUT**: 
 - R^2 of model
 
Above, you fit a regression line to illustrate the relationship between cluster average wealth and corresponding cluster nightlights. Now, use [cross-validation](https://en.wikipedia.org/wiki/Cross-validation_%28statistics%29) to get a better sense of out of sample accuracy.

There are two options for this. The basic way, for those new to machine learning, is to randomly divide your dataset into a training and a test dataset. Randomly select 80% of your clusters and fit a model of cluster-average DHS wealth (your response/dependent variable) on nightlights (your predictor/independent variables). You can use a regression or any other model you prefer. Then, use that model to predict the wealth of the remaining 20% of your data, and compare the predicted values to the actual values, and report the R^2 on these 20%.

The preferred way is to use 10-fold cross-validation, where you repeat the above procedure 10 times, so that you have 10 different and non-overlapping test sets. Then, you report the cross-validated R^2 of your model (i.e., the average R^2 of your 10 test folds).

Hints:
 - The scikit learn library has built-in functions for [cross-validation](http://scikit-learn.org/stable/modules/cross_validation.html) that make this quite easy.
 


In [ ]:
from sklearn.model_selection import KFold
from sklearn.linear_model import Ridge

# from sklearn.model_selection import cross_val_score

def values (df, col):
    # http://stackoverflow.com/questions/30813044/sklearn-found-arrays-with-inconsistent-numbers-of-samples-when-calling-linearre
    vals     = df[col].values
    dim      = vals.shape[0]
    reshaped = vals.reshape(dim, 1)
    return reshaped

regr = Ridge()
scores = cross_val_score(regr, 
                         values(wealth_nightlights, 'wealth'), 
                         values(wealth_nightlights, 'mean_'), 
                         cv=10, scoring='r2')

np.mean(scores)


# 4. Download daytime satellite imagery 
- **INPUT**: 
 - Google Maps API key
 - `Sector_Boundary_2012.shp`: Rwandan shapefile
- **OUTPUT**: 
 - Thousands of satellite images (store in directory `google_image/`)

We will use the Google Static Maps API to download satellite images. Refer [Google Static Maps introduction](https://developers.google.com/maps/documentation/static-maps/intro) and [Google Static Maps API Usage Limits](https://developers.google.com/maps/documentation/static-maps/usage-limits). You must apply for an API key before downloading. ** Note that it may take you several days to download the required images, so start early!**

Download the images from Google at zoom level 16 (pixel resolution is about 2.5m). Set the image size to be 400 pixels X 400 pixels, so that each image you download will cover 1 square kilometer. In this way, each daytime image you download will correspond to a single pixel from the nighttime imagery from Step 1 above.

Hints:
 - You will need to tell Google the locations for which you wish to download images. One way to do this is to use a [shapefiles](https://en.wikipedia.org/wiki/Shapefile) that specifies the borders of Rwanda. We have provided this shapefile (`Sector_Boundary_2012.shp`) as well as a helper function to read in the shapefile.
 - You can organize the files however you like. However, for later analysis (Steps 6 and beyond), it may help if you organize these daytime images into 64 folders, with one folder indicating the nightlight intensity of the pixel corresponding to the daytime image. In other words, if you download a daytime image for which the corresponding nighttime pixel has value 32, store that daytime image in a folder labeled '32'. This way, all the satellite images within each folder will have the same nightlight intensity. The file name is columnIndex_rowIndex.jpg, in which row index and column index are the index in the nightlight image (See the diagram below).

![title](figure/data_description.png)

In [467]:
# Helper function to read a shapefile
def get_shp_extent(shp_file):
    """
    Function
    --------
    get_shp_extent

    Given a shapefile, get the extent (boundaries)

    Parameters
    ----------
    shp_file : string
        Path to the shapefile
    
    Returns
    -------
    extent : tuple
        Boundary location of the shapefile (x_min, x_max, y_min, y_max)
    """
    inDriver = ogr.GetDriverByName("ESRI Shapefile")
    inDataSource = inDriver.Open(inShapefile, 0)
    inLayer = inDataSource.GetLayer()
    extent = inLayer.GetExtent()
    # x_min_shp, x_max_shp, y_min_shp, y_max_shp = extent
    return extent

In [ ]:
# Helper functions to download images from Google Maps API

from retrying import retry

@retry(wait_exponential_multiplier=1000, wait_exponential_max=3600000)
def save_img(url, file_path, file_name):
    """
    Function
    --------
    save_img

    Given a url of the map, save the image

    Parameters
    ----------
    url : string
        URL of the map from Google Map Static API
    file_path : string
        Folder name of the map
    file_name : string
        File name
    
    Returns
    -------
    None
    """
    a = urllib.request.urlopen(url).read()
    b = BytesIO(a)
    image = ndimage.imread(b, mode='RGB')
    # when no image exists, api will return an image with the same color. 
    # and in the center of the image, it said'Sorry. We have no imagery here'.
    # we should drop these images if large area of the image has the same color.
    if np.array_equal(image[:,:10,:],image[:,10:20,:]):
        pass
    else:
        misc.imsave(file_path + file_name, image[50:450, :, :])

# Now read in the shapefile for Rwanda and extract the edges of the country
inShapefile = 'provided/Sector_Boundary_2012/Sector_Boundary_2012.shp'
x_min_shp, x_max_shp, y_min_shp, y_max_shp = get_shp_extent(inShapefile)

left_idx, top_idx = get_cell_idx(x_min_shp, y_max_shp, top_left_x_coords, top_left_y_coords)
right_idx, bottom_idx = get_cell_idx(x_max_shp, y_min_shp, top_left_x_coords, top_left_y_coords)

key = 'AIzaSyBJ0FEnlPhABevqPJNNBqG8jxUqZPv8cZ4'
m = 1
#python2's `xrange` is now `range` in python3
for i in range(left_idx, right_idx + 1):
    for j in range(top_idx, bottom_idx + 1):
        lon = centroid_x_coords[i]
        lat = centroid_y_coords[j]
        url = 'https://maps.googleapis.com/maps/api/staticmap?center=' + str(lat) + ',' + \
               str(lon) + '&zoom=16&size=400x500&maptype=satellite&key=' + key
        lightness = bands_data[j, i, 0]
        file_path = 'google_image/' + str(lightness) + '/'
        if not os.path.isdir(file_path):
            os.makedirs(file_path)
        file_name = str(i) + '_' + str(j) +'.jpg'
        save_img(url, file_path, file_name)
        if m % 100 == 0:
            print(m)
        m += 1

reached
got a
got b
got image [[[ 76 104 104]
  [ 88 120 120]
  [ 80 112 108]
  ..., 
  [100 130 130]
  [ 88 116 116]
  [104 135 131]]

 [[ 64  96  96]
  [ 88 120 124]
  [ 84 120 120]
  ..., 
  [ 92 120 120]
  [ 84 112 112]
  [112 143 141]]

 [[ 64  92 100]
  [104 135 139]
  [112 143 141]
  ..., 
  [ 68  96 100]
  [ 88 120 116]
  [ 80 112 108]]

 ..., 
 [[ 72 100 112]
  [ 64  92 104]
  [ 68  96 108]
  ..., 
  [ 25  35  36]
  [ 25  35  36]
  [ 25  35  36]]

 [[ 60  92 104]
  [ 72 104 112]
  [ 72 104 112]
  ..., 
  [ 30  40  42]
  [ 25  35  36]
  [ 25  35  36]]

 [[ 56  88  96]
  [ 52  84  92]
  [ 64  96 104]
  ..., 
  [ 30  40  42]
  [ 25  35  36]
  [ 25  35  36]]]
reached
got a
got b
got image [[[ 76 112 112]
  [ 64  96  96]
  [ 80 116 112]
  ..., 
  [ 56  84  90]
  [ 64  92  98]
  [ 57  89  91]]

 [[ 76 108 108]
  [ 57  89  91]
  [ 72 108 104]
  ..., 
  [ 80 112 112]
  [ 84 112 116]
  [ 84 112 116]]

 [[104 135 135]
  [ 88 120 120]
  [ 83 120 115]
  ..., 
  [ 88 120 124]
  [ 68  96 10

# 5. Test whether basic features of daytime imagery can predict wealth
In step 3, you tested whether nightlight imagery could predict the wealth of Rwandan villages. You will now test whether daytime imagery can predict village wealth. Start by extracting simple metrics from the daytime imagery; in step 6 you will use more sophsticated methods to engineer these features from the images. **You don't need to do this step if you are able to do step 6.**

## 5.1. Extract "basic" features from daytime imagery
- **INPUT**: 
 - `google_image/...`: Raw images, from Step 4
- **OUTPUT**: 
 - `google_image_features_basic.csv`: Image features 

Convert the raw data from the satellite imagery into a set of features that can be used in a machine learning algorithm. A simple way to do this is to take the raw R/G/B values for each pixel and average them for the image. Thus, if an image has 100 pixels, you will have an average R value, an average G value, and an average B value. Create more features by also computing the min, max, median, and standard deviation of R, G, and B for each image. This process will convert each image into a vector of 15 features.

Feel free to be creative if you wish to generate additional features from the imagery -- this is similar to the process described in section 2.3 of the paper's supplementary materials. But don't waste too much time, and don't expect these features to be terribly useful.

In [0]:
#
# Your code here
#

## 5.2. Merge daytime images with DHS data

- **INPUT**: 
 - `google_image_features_basic.csv`: Satellite imagery features, from Step 5.1
 - `rwanda_cluster_avg_asset_2010.csv`: DHS cluster averages, from Step 2
- **OUTPUT**: Merged datasets
 - `data/model/DHS_daytime.csv`: Merged dataset with 492 rows, and 16 columns (one indicates average cluster wealth, 15 daytime image features)

Now that you have feature vectors for each image, you should merge these with the DHS data indicated average cluster wealth. Follow a similar procedure as you did with 3.1, i.e., determine which image feature vectors are associated with each cluster, and then calculate, for each cluster, the average value of each feature.

Save your output as `DHS_daytime.csv` and check that it is roughly the same as the file we have provided. There may be slight differences if you chose to calculate a different set of features than those described in 5.1.

In [42]:
#
# Your code here
#

## 5.3. Fit a model of wealth as a function of basic daytime features
- **INPUT**: 
 - `data/model/DHS_daytime.csv`, from Step 5.2
- **OUTPUT**: 
 - R^2 of model
 
As in 3.2, use 10-fold cross-validation to fit a model of cluster-level DHS wealth (your response/dependent variable) as a function of the nightlights data (your predictor/independent variables). Since you have a reasonably large number of predictor variables, you should use a model that incorporates some form of regularization (e.g., ridge regression, lasso regression, or a tree-based method).  Report the cross-validated R^2 of your model (i.e., the average R^2 of your 10 test folds).


In [0]:
#
# Your code here
#

# 6. Extract features from daytime imagery using deep learning libraries

This is where things get interesting. Above, you have seen that the RGB features of the daytime images are not great at predicting cluster average wealth (why not?). Now, you will use existing libraries to extract more meaningful features from the daytime imagery, similar to what is shown in Fig. 2 of the paper.

## 6.1. Use the keras library to use a basic CNN to extract features of the daytime images 
 
- **INPUT**: 
 - `google_image/...`: Raw images, from Step 4
- **OUTPUT**: 
 - `google_image_features_cnn.csv`: Image features 

Begin by using a Convolutional Neural Network that has been pre-trained on ImageNet to extract features from the images. We recommend using the [`Keras` library](https://keras.io/), which provides a very straightforward interface to [TensorFlow](https://www.tensorflow.org/).

Hints:
 - This [short intro](https://github.com/fchollet/deep-learning-models/blob/master/README.md) will help you get started with extracting features from the CNN.

In [0]:
#
# Your code here
#

# 6.2. Test whether these new features of satellite imagery can predict wealth
- **INPUT**: 
 - `google_image_features_cnn.csv`: Satellite imagery features, from Step 6.1
 - `rwanda_cluster_avg_asset_2010.csv`: DHS cluster averages, from Step 2
- **OUTPUT**: 
 - `data/model/DHS_daytime.csv`: Merged dataset with 492 rows, and 4097 columns (one indicates average cluster wealth, 4096 CNN-based features)
 - R^2 of model
 
Calculate the average value of each feature for each of the DHS clusters. As in Step 3.1 and 5.2, you will want to aggregate over images near the cluster centroid by taking the average value for each feature. Create a scatterplot showing the relationship between average cluster wealth (y-axis) and the first principal component of all of your image features (x-axis) - in other words, run PCA on your 4096 image features and plot the first PC on the x-axis. Your scatterplot should have one dot for each of the 492 DHS clusters.

Use 10-fold cross-validation to fit a model of cluster-level DHS wealth (your response/dependent variable) as a function of the "deep" features (your predictor/independent variables). Use a model that incorporates some form of regularization (e.g., ridge regression, lasso regression, or a tree-based method).  Report the cross-validated R^2 of your model (i.e., the average R^2 of your 10 test folds).

In [2]:
from sklearn.decomposition import PCA
#
# Your code here
#

# 7. Extra Credit 1: Replicate final model and results of Jean et al (2016)

The only thing missing at this point is the "transfer learning" step. In other words, instead of using the image features extracted by the CNN directly, we want to retrain the CNN to predict nightlights from daytime imagery, and use those features, which presumably are more appropriate to our final prediction task.

## 7.1. Use the nightlights to retrain the CNN and extract features

- **INPUT**: 
 - `google_image/...`: Raw images, from Step 4
- **OUTPUT**: 
 - `google_image_features_cnn_retrained.csv`: Image features 

Following the approach used in the paper, first divide your daytime images into three groups, corresponding to images where the corresponding night-lights pixel is dim, medium, or bright. Use these values to define your groups: [0, 3), [3, 35), [35, 64). We have given you the code to do this below.

In [0]:
#
# Your code here
#

## 7.2. Test whether "deep" features of satellite imagery can predict wealth
- **INPUT**: 
 - `google_image_cnn/...`: Satellite images from 7.1
- **OUTPUT**: 
 - `data/model/DHS_CNN.csv`: Merged dataset with 492 rows, and 4097 columns (one indicates average cluster wealth, 4096 CNN features)
 - R^2 of model

Repeat 6.2, except this time use the features generated from 7.1, i.e., the features that have been constructed after transfer learning. As in 6.2, show a scatterplot of the relationship between average cluster wealth (y-axis) and the first principal component of your image features. Then, report the cross-validated R^2 of your model (i.e., the average R^2 of your 10 test folds).

In [0]:
#
# Your code here
#

# 8. Extra Credit 2: Construct a high-resolution map of the distribution of predicted wealth
- **INPUT**: 
 - Model, image features (data/model/features_all_predictimage_location.csv)
- **OUTPUT**: 
 - Map ('poverty_mapping.tiff')
 
Choose your favorite model from the three daytime-based models that you have trained above: 5.3 (basic daytime features), 6.2 (deep daytime features), or 7.2 (transfer-learned daytime features). Use this model to calculate the predicted wealth of every one of your original images. Create a heatmap showing the distribution of predicted wealth in Rwanda. With any luck, it will look something like this:
<img src="figure/pmap.png" alt="Map"/>

In [0]:
#
# Your code here
#